# Generated by Django 3.0.7 on 2021-03-14 21:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=8),
        ),
    ]
