# Generated by Django 3.0.7 on 2021-03-14 21:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20210314_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
