# Generated by Django 3.0.7 on 2021-03-14 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20210314_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detsale',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.Product'),
        ),
    ]
