# Generated by Django 3.0.7 on 2021-03-14 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20210314_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='cli',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.Client'),
        ),
    ]
